# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jiwchoi <jiwchoi@student.42seoul.k>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/05 11:56:58 by jiwchoi           #+#    #+#              #
#    Updated: 2021/03/05 14:03:10 by jiwchoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	debian:buster
LABEL	maintainer="jiwchoi@student.42seoul.kr"

RUN		apt-get update && apt-get -y upgrade && apt-get install -y \
		nginx \
		openssl \
		vim \
		php7.3-fpm \
		mariadb-server \
		php-mysql \
		wget

COPY	./srcs/run.sh ./
COPY	./srcs/default ./tmp
COPY	./srcs/wp-config.php ./tmp
COPY	./srcs/config.inc.php ./tmp

EXPOSE	80 443

CMD		bash run.sh
